version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_USER=dbtodbtest
      - MYSQL_PASSWORD=dbtodbtest
      - MYSQL_DATABASE=dbtodbtest
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    expose:
      - 3306